"""empty message

Revision ID: 8431c81a675d
Revises: 
Create Date: 2018-08-15 21:24:40.775032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8431c81a675d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('from_', sa.String(length=100), nullable=False),
    sa.Column('to', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'from_', 'to', name='_date_from_to_uc')
    )
    op.create_table('exchange_rate_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_', sa.String(length=100), nullable=False),
    sa.Column('to', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_', 'to', name='_from_to_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_rate_list')
    op.drop_table('exchange_rate_history')
    # ### end Alembic commands ###
